export { NotificationCreateMutationArgs } from 'src/platformClient/platformNotificationClient/types/notification-create.type'
export { NotificationWeb } from 'src/platformClient/platformNotificationClient/types/notification-web.type'
export { Notification } from 'src/platformClient/platformNotificationClient/types/notification.type'
export { NotificationUserGroup } from 'src/platformClient/platformNotificationClient/types/notification-user-group.type'
export { NotificationRecipient } from 'src/platformClient/platformNotificationClient/types/notification-recipient.type'
